Parameters: 
  InstanceTypeParameter: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.nano
      - t2.small
    Description: Enter t2.micro, t2.nano, or t2.small. Default is t2.micro.
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-02396cdd13e9a1257
      InstanceType: 
        Ref: InstanceTypeParameter